pruebaDispersion: pruebaDispersion.c dispersion.o dispersion.h
	gcc -g pruebaDispersion.c dispersion.o -o pruebaDispersion
	
monticulo.o: dispersion.c dispersion.h
	gcc -c dispersion.c

clean:
	rm *.o