calorias.jar: Calorias.class CaloryAdder.class DishEditor.class Dishes.class
	jar cmfv manifest calorias.jar *.class com/coti/*/*.class

Calorias.class: Calorias.java
	javac Calorias.java

DishEditor.class: DishEditor.java
	javac DishEditor.java

Dishes.class: Dishes.java
	javac Dishes.java

CaloryAdder.class: CaloryAdder.java
	javac CaloryAdder.java

