program.jar: EscribirMilNumerosTerminal.class
	jar cmfv manifest program.jar EscribirMilNumerosTerminal.class


EscribirMilNumerosTerminal.class : EscribirMilNumerosTerminal.java
	javac EscribirMilNumerosTerminal.java


lean:
	rm -rf *.class
	rm -rf /com/coti/guitools/*.class
	rm -rf /com/coti/textfiletools/*.class
clean:
	rm -rf *.class
	rm -rf program.jar
