program.jar: EscribirMilNumeros.class   
	jar cmfv manifest program.jar EscribirMilNumeros.class  




EscribirMilNumeros.class : EscribirMilNumeros.java 
	javac EscribirMilNumeros.java 


lean:
	rm -rf *.class
	rm -rf /com/coti/guitools/*.class
	rm -rf /com/coti/textfiletools/*.class
clean:
	rm -rf *.class
	rm -rf program.jar
