program.jar: LeerNumeros.class   
	jar cmfv manifest program.jar LeerNumeros.class  




LeerNumeros.class : LeerNumeros.java 
	javac LeerNumeros.java 


lean:
	rm -rf *.class
	rm -rf /com/coti/guitools/*.class
	rm -rf /com/coti/textfiletools/*.class
clean:
	rm -rf *.class
	rm -rf program.jar
