program.jar: EscribirMilNumerosEscritorio.class   
	jar cmfv manifest program.jar EscribirMilNumerosEscritorio.class  




EscribirMilNumerosEscritorio.class : EscribirMilNumerosEscritorio.java 
	javac EscribirMilNumerosEscritorio.java 


lean:
	rm -rf *.class

clean:
	rm -rf *.class
	rm -rf program.jar
