# Ejercicio 1
cMatrices:prueba.c conjuntosM/conjuntos.o  
	gcc -g prueba.c -DMATRICES conjuntosM/conjuntos.o -o cMatrices
conjuntosM/conjuntos.o: conjuntosM/conjuntos.c conjuntosM/conjuntos.h
	gcc -c -g conjuntosM/conjuntos.c -o conjuntosM/conjuntos.o
# Ejercicio 2
cListas:prueba.c conjuntosL/conjuntos.o 
	gcc -g prueba.c -DLISTAS conjuntosL/conjuntos.o -o cListas
conjuntosL/conjuntos.o: conjuntosL/conjuntos.c conjuntosL/conjuntos.h
	gcc -c -g conjuntosL/conjuntos.c -o conjuntosL/conjuntos.o
# Ejercicio 3 
cArboles:prueba.c conjuntosA/conjuntos.o 
	gcc -g prueba.c -DARBOLES conjuntosA/conjuntos.o -o cArboles
conjuntosA/conjuntos.o: conjuntosA/conjuntos.c conjuntosA/conjuntos.h
	gcc -c -g conjuntosA/conjuntos.c -o conjuntosA/conjuntos.o

