program.jar: Main.class   
	jar cmfv manifest program.jar Main.class  




Main.class : Main.java 
	javac Main.java 


lean:
	rm -rf *.class
	rm -rf /com/coti/guitools/*.class
	rm -rf /com/coti/textfiletools/*.class
clean:
	rm -rf *.class
	rm -rf program.jar
